name: neuromorph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - tensorflow==2.13.0
      - tensorflow-addons==0.21.0
      - ipython
      - albumentations
      - nibabel
      - scipy
      - typeguard
      - opencv-python
      - elasticdeform
      - loguru
      - pydantic
      - pandas
      - pymeshlab
      - plotly
      - seaborn
      - open3d
      - vtk
      - fast_simplification
      - nvidia-ml-py3
      - pyvista
      - psutil
      - pynvml
      - scikit-image
      - tqdm
      - openneuro-py
